name: Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'elm.json'
      - 'elm-stuff/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - run: elm make src/Main.elm
      - name: git setting
        run: |
          git config --local user.email "kachick1@gmail.com"
          git config --local user.name "Kenichi Kamiya"
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d-%H%M-UTC"`
          BRANCH_NAME="deploy-$DATE"
          git checkout gh-pages
          git checkout -b "$BRANCH_NAME"
          git add index.html
          git commit -m 'Update with latest code'
          git push origin "$BRANCH_NAME":gh-pages
